spring.application.name=service-discovery

spring.config.import=optional:file:local.env[.properties]
server.port=${SERVICE_DISCOVERY_PORT}

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=http://localhost:${server.port}/eureka/